### PR TITLE
Tests, dependencies and documentation update

### PR DESCRIPTION
**Pull request by Basil-Courbayre-Dussau**

### CODE REVIEW

**Comment by Basil-Courbayre-Dussau** [comment]
@antagomir @TuomasBorman Do these little modifications look ok to you?

**Comment by antagomir** [comment]
Seems good to me. Is this getting ready for PR to upstream (LTLA)?

**Comment by antagomir** [comment]
Also note you can request reviewers from top right panel.

**Comment by Basil-Courbayre-Dussau** [comment]
> Also note you can request reviewers from top right panel.

I could do that on my OMA PR but but on this one I can't manage the top right panel. Maybe I don't have the rights.

**Comment by Basil-Courbayre-Dussau** [comment]
> Seems good to me. Is this getting ready for PR to upstream (LTLA)?

Yes, it should be merged soon. This is the second version of the code after the suggestions made in [#14](https://github.com/LTLA/bluster/pull/14).

**Review by TuomasBorman — APPROVED** [review]

**Comment by TuomasBorman** [comment]
> > Also note you can request reviewers from top right panel.
> 
> I could do that on my OMA PR but but on this one I can't manage the top right panel. Maybe I don't have the rights.

Not sure, but this modification comes from your fork; I guess in OMA you modified directly OMA::branch --> this might be the reason?

**Comment by Basil-Courbayre-Dussau** [comment]
> 

True, that could also be it.

**Pull request merged**
