### PR TITLE
Addition of the contributors to the DESCRIPTION file

### PR DESCRIPTION
**Pull request by Basil-Courbayre-Dussau**
Added Leo, Tuomas and myself as contributors.

### CODE REVIEW

**Comment by TuomasBorman** [comment]
I think you could still add to dist.fun the function requirement. Must have method parameter for specifying dissimilarity measure. And its output must be dissimilarity matrix. --> if those requirements are not fulfilled it leads to an error (it could be good to notify user.)

**Comment by Basil-Courbayre-Dussau** [comment]
How is that @TuomasBorman ?

**Comment by TuomasBorman** [comment]
Hmmm, how about

`@param dist.fun Function specifying the function to use to compute the distance matrix. Must be stats::dist-like function.`

Is that clear? What you think?

**Comment by Basil-Courbayre-Dussau** [comment]
It's clear if people reading know what you mean. I can do a mix of the two `@param dist.fun Function specifying the function to use to compute the distance matrix. Must be stats::dist-like function. i.e. takes a method as a parameter and returns a dissimilarity matrix`
Is that ok?

**Comment by TuomasBorman** [comment]
Yes, sounds feasible

**Comment by Basil-Courbayre-Dussau** [comment]
Is this version ok to merge @TuomasBorman ?

**Review by TuomasBorman — APPROVED** [review]
feuer frei

**Pull request merged**
